Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.projectName}-${self:custom.stage}-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  # Set up an app client for website frontend
  CognitoUserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.projectName}-${self:custom.stage}-web-client
      UserPoolId:
        Ref: CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolWebClientId:
    Value:
      Ref: CognitoUserPoolWebClient
