Resources:
  SetupCognitoOAuth:
    Type: Custom::SetupCognitoOAuth
    DependsOn: [CognitoUserPool]
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - ConfigureCognitoLambdaFunction # the logical ID in CF stack, which is the capitalized function name in serverless.yml + 'LambdaFunction'
          - Arn
      UserPoolID:
        Ref: CognitoUserPool
