Resources:
  SetupCognitoOAuth:
    Type: Custom::SetupCognitoOAuth
    DependsOn: [CognitoUserPool]
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - ConfigureCognitoLambdaFunction
          - Arn
      UserPoolID:
        Ref: CognitoUserPool